// cligen reads bron-open-api-public.json and emits cobra command definitions
// under generated/. The derivation rules are documented in BRO-486.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// resourceAliases — short/disambiguated CLI names for select URL segments.
var resourceAliases = map[string]string{
	"address-book-records": "address-book",
	"addresses":            "deposit-addresses",
}

// endpointAliases — full (method,path) overrides for endpoints that logically
// belong under a different resource.
var endpointAliases = map[string]string{
	"GET /dictionary/asset-market-prices":  "assets prices",
	"GET /dictionary/symbol-market-prices": "symbols prices",
}

// httpMethods — keys under an OpenAPI path item that represent operations.
var httpMethods = map[string]struct{}{
	"get": {}, "post": {}, "put": {}, "patch": {},
	"delete": {}, "options": {}, "head": {}, "trace": {},
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: cligen <openapi.json> [out-dir]")
		os.Exit(2)
	}
	specPath := os.Args[1]
	outDir := "generated"
	if len(os.Args) >= 3 {
		outDir = os.Args[2]
	}

	data, err := os.ReadFile(specPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "read spec:", err)
		os.Exit(1)
	}

	var spec rawSpec
	if err := json.Unmarshal(data, &spec); err != nil {
		fmt.Fprintln(os.Stderr, "parse spec:", err)
		os.Exit(1)
	}

	plan, err := buildPlan(spec)
	if err != nil {
		fmt.Fprintln(os.Stderr, "build plan:", err)
		os.Exit(1)
	}
	sort.Slice(plan, func(i, j int) bool {
		if plan[i].Resource != plan[j].Resource {
			return plan[i].Resource < plan[j].Resource
		}
		return plan[i].Verb < plan[j].Verb
	})

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mkdir out:", err)
		os.Exit(1)
	}
	shortcuts := collectTxShortcuts(spec)
	src, err := emit(plan, shortcuts)
	if err != nil {
		fmt.Fprintln(os.Stderr, "emit:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(outDir, "commands.go"), src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write commands.go:", err)
		os.Exit(1)
	}

	// helpdoc.go — HelpEntries map used by `bron schema` / `bron help-json`
	helpSrc, err := emitHelpDoc(plan, shortcuts)
	if err != nil {
		fmt.Fprintln(os.Stderr, "emit helpdoc:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(outDir, "helpdoc.go"), helpSrc, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write helpdoc.go:", err)
		os.Exit(1)
	}

	// spec.go + spec.json — embedded raw OpenAPI for schema lookup at runtime
	if err := os.WriteFile(filepath.Join(outDir, "spec.json"), data, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write spec.json:", err)
		os.Exit(1)
	}
	specSrc := []byte(`// Code generated by cligen. DO NOT EDIT.
package generated

import _ "embed"

//go:embed spec.json
var Spec []byte
`)
	if err := os.WriteFile(filepath.Join(outDir, "spec.go"), specSrc, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write spec.go:", err)
		os.Exit(1)
	}

	fmt.Printf("generated %s/{commands,helpdoc,spec}.go (%d endpoints, %d tx-types)\n", outDir, len(plan), len(shortcuts))
}

// --- tx <type> shortcuts ---

type txShortcut struct {
	Key       string   // "withdrawal", "stake-delegation"
	Class     string   // "WithdrawalParams"
	TopFields []string // CreateTransaction top-level fields except transactionType and params
	Params    []string // dot-paths under "params." (without prefix)
}

// txKeyOverrides handles class→key mismatches that the algorithm can't infer.
// Keep tiny; rationale documented in BRO-486.
var txKeyOverrides = map[string]string{
	"StakeUnDelegationParams": "stake-undelegation",
}

func collectTxShortcuts(spec rawSpec) []txShortcut {
	reg := spec.Components.Schemas
	create, ok := reg["CreateTransaction"]
	if !ok {
		return nil
	}

	// Authoritative list of valid transactionType values (from the enum schema).
	// Shortcuts are only emitted for keys present in this set, so we never produce
	// a `bron tx <type>` that the API would reject.
	validTypes := map[string]bool{}
	if tt, ok := reg["TransactionType"]; ok {
		for _, v := range tt.Enum {
			if s, ok := v.(string); ok {
				validTypes[s] = true
			}
		}
	}

	// Collect top-level fields that are scalars/arrays — skip transactionType (fixed by shortcut)
	// and skip params (handled per shortcut below).
	var topFields []string
	for name, prop := range create.Properties {
		if name == "transactionType" || name == "params" {
			continue
		}
		switch propKind(prop, reg) {
		case "scalar", "array":
			topFields = append(topFields, name)
		}
	}
	sort.Strings(topFields)

	paramsProp, ok := create.Properties["params"]
	if !ok || len(paramsProp.OneOf) == 0 {
		return nil
	}

	seen := map[string]bool{}
	var out []txShortcut
	for _, p := range paramsProp.OneOf {
		if p.Ref == "" {
			continue
		}
		cls := refName(p.Ref)
		if seen[cls] {
			continue
		}
		seen[cls] = true

		key, ok := txKeyOverrides[cls]
		if !ok {
			key = classToKey(cls)
		}
		// Skip Params classes whose derived key isn't a real transactionType.
		// Avoids exposing dead `bron tx <type>` commands the API would reject.
		if len(validTypes) > 0 && !validTypes[key] {
			continue
		}

		out = append(out, txShortcut{
			Key:       key,
			Class:     cls,
			TopFields: topFields,
			Params:    collectLeaves(p, "", reg),
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Key < out[j].Key })
	return out
}

// classToKey converts a Params class name to its kebab-case TransactionType key.
// "WithdrawalParams" → "withdrawal"; "StakeDelegationParams" → "stake-delegation".
func classToKey(cls string) string {
	s := strings.TrimSuffix(cls, "Params")
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('-')
			}
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// --- spec types ---

type rawSpec struct {
	Paths      map[string]map[string]json.RawMessage `json:"paths"`
	Components struct {
		Schemas map[string]rawSchema `json:"schemas"`
	} `json:"components"`
}

type rawOp struct {
	Summary     string                 `json:"summary"`
	Tags        []string               `json:"tags"`
	Parameters  []rawParam             `json:"parameters"`
	RequestBody *rawReqBody            `json:"requestBody"`
	Responses   map[string]rawResponse `json:"responses"`
}

type rawResponse struct {
	Content map[string]rawContent `json:"content"`
}

type rawParam struct {
	Name     string     `json:"name"`
	In       string     `json:"in"`
	Required bool       `json:"required"`
	Schema   *rawSchema `json:"schema"`
}

type rawReqBody struct {
	Content map[string]rawContent `json:"content"`
}

type rawContent struct {
	Schema rawSchema `json:"schema"`
}

type rawSchema struct {
	Type       string               `json:"type"`
	Ref        string               `json:"$ref"`
	Properties map[string]rawSchema `json:"properties"`
	Required   []string             `json:"required"`
	Items      *rawSchema           `json:"items"`
	OneOf      []rawSchema          `json:"oneOf"`
	AnyOf      []rawSchema          `json:"anyOf"`
	AllOf      []rawSchema          `json:"allOf"`
	Enum       []interface{}        `json:"enum"`
}

// --- planning ---

type plannedCmd struct {
	Method      string
	Path        string
	Resource    string
	Verb        string
	PathArgs    []string // names from URL placeholders, in order
	QueryParams []param
	BodyFields  []string // dot-paths for --<flag> body field overlay (skips oneOf)
	HasBody     bool
	BodyRef     string // component name of request body schema (e.g. "CreateTransaction")
	ResponseRef string // component name of 200/201 response schema (e.g. "Transactions")
}

type param struct {
	Name     string
	Required bool
}

func buildPlan(spec rawSpec) ([]plannedCmd, error) {
	registry := spec.Components.Schemas

	var out []plannedCmd
	for route, methods := range spec.Paths {
		for key, raw := range methods {
			if _, ok := httpMethods[strings.ToLower(key)]; !ok {
				continue
			}
			var op rawOp
			if err := json.Unmarshal(raw, &op); err != nil {
				return nil, fmt.Errorf("path %q method %q: %w", route, key, err)
			}
			method := strings.ToUpper(key)
			cmd := derive(method, route)
			for _, p := range op.Parameters {
				if p.In == "query" {
					cmd.QueryParams = append(cmd.QueryParams, param{Name: p.Name, Required: p.Required})
				}
			}
			if op.RequestBody != nil {
				cmd.HasBody = true
				if jc, ok := op.RequestBody.Content["application/json"]; ok {
					cmd.BodyFields = collectLeaves(jc.Schema, "", registry)
					if jc.Schema.Ref != "" {
						cmd.BodyRef = refName(jc.Schema.Ref)
					}
				}
			}
			for _, code := range []string{"200", "201"} {
				if resp, ok := op.Responses[code]; ok {
					if jc, ok := resp.Content["application/json"]; ok && jc.Schema.Ref != "" {
						cmd.ResponseRef = refName(jc.Schema.Ref)
						break
					}
				}
			}
			out = append(out, cmd)
		}
	}
	return out, nil
}

// derive applies the algorithm from BRO-486 with alias overrides.
func derive(method, path string) plannedCmd {
	if alias, ok := endpointAliases[method+" "+path]; ok {
		_, args := splitPath(path)
		return plannedCmd{Method: method, Path: path, Resource: firstWord(alias), Verb: tail(alias), PathArgs: args}
	}

	stripped := stripPrefix(path)
	segments := splitSegments(stripped)

	if len(segments) == 0 {
		return plannedCmd{Method: method, Path: path, Resource: "workspace", Verb: "info"}
	}

	resource := segments[0]
	if alias, ok := resourceAliases[resource]; ok {
		resource = alias
	}

	tailSeg := segments[1:]
	var ids []string
	var verbParts []string
	for _, s := range tailSeg {
		if isPlaceholder(s) {
			ids = append(ids, strings.TrimSuffix(strings.TrimPrefix(s, "{"), "}"))
		} else {
			verbParts = append(verbParts, s)
		}
	}

	verb := strings.Join(verbParts, " ")
	if verb == "" {
		switch method {
		case "GET":
			if len(ids) == 0 {
				verb = "list"
			} else {
				verb = "get"
			}
		case "POST":
			verb = "create"
		case "PUT", "PATCH":
			verb = "update"
		case "DELETE":
			verb = "delete"
		default:
			verb = strings.ToLower(method)
		}
	}
	return plannedCmd{Method: method, Path: path, Resource: resource, Verb: verb, PathArgs: ids}
}

var stripPrefixes = []string{"/workspaces/{workspaceId}", "/dictionary"}

func stripPrefix(p string) string {
	for _, pref := range stripPrefixes {
		if strings.HasPrefix(p, pref) {
			return strings.TrimPrefix(p, pref)
		}
	}
	return p
}

func splitSegments(p string) []string {
	parts := strings.Split(p, "/")
	out := parts[:0]
	for _, x := range parts {
		if x != "" {
			out = append(out, x)
		}
	}
	return out
}

func splitPath(p string) (string, []string) {
	stripped := stripPrefix(p)
	segs := splitSegments(stripped)
	var ids []string
	for _, s := range segs {
		if isPlaceholder(s) {
			ids = append(ids, strings.TrimSuffix(strings.TrimPrefix(s, "{"), "}"))
		}
	}
	return stripped, ids
}

func isPlaceholder(s string) bool {
	return len(s) >= 2 && s[0] == '{' && s[len(s)-1] == '}'
}

func firstWord(s string) string {
	i := strings.IndexByte(s, ' ')
	if i < 0 {
		return s
	}
	return s[:i]
}

func tail(s string) string {
	i := strings.IndexByte(s, ' ')
	if i < 0 {
		return ""
	}
	return s[i+1:]
}

// --- schema walking ---

// collectLeaves returns the dot-paths of every scalar/array leaf reachable from schema.
// Refs are resolved via registry. oneOf/anyOf branches are skipped (no discriminator,
// can't pick a shape). allOf is treated as union of properties.
func collectLeaves(s rawSchema, prefix string, reg map[string]rawSchema) []string {
	var out []string
	visited := map[string]bool{}
	walkLeaves(s, prefix, reg, visited, &out)
	sort.Strings(out)
	return out
}

func walkLeaves(s rawSchema, prefix string, reg map[string]rawSchema, visited map[string]bool, out *[]string) {
	if s.Ref != "" {
		name := refName(s.Ref)
		if visited[name] {
			return
		}
		visited[name] = true
		defer delete(visited, name)
		s = reg[name]
	}
	if len(s.OneOf) > 0 || len(s.AnyOf) > 0 {
		return
	}
	for _, child := range s.AllOf {
		walkLeaves(child, prefix, reg, visited, out)
	}
	for name, prop := range s.Properties {
		dot := name
		if prefix != "" {
			dot = prefix + "." + name
		}
		switch propKind(prop, reg) {
		case "scalar", "array":
			*out = append(*out, dot)
		case "object":
			walkLeaves(prop, dot, reg, visited, out)
		}
	}
}

func propKind(s rawSchema, reg map[string]rawSchema) string {
	if s.Ref != "" {
		s = reg[refName(s.Ref)]
	}
	if len(s.OneOf) > 0 || len(s.AnyOf) > 0 {
		return "skip"
	}
	switch s.Type {
	case "string", "integer", "number", "boolean":
		return "scalar"
	case "array":
		return "array"
	case "object":
		return "object"
	}
	if len(s.Properties) > 0 {
		return "object"
	}
	return "scalar" // unknown → treat as scalar so user can still set it via --flag
}

func refName(ref string) string {
	parts := strings.Split(ref, "/")
	return parts[len(parts)-1]
}

// --- emission ---

func emit(plan []plannedCmd, shortcuts []txShortcut) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintln(&b, "// Code generated by cligen. DO NOT EDIT.")
	fmt.Fprintln(&b, "package generated")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `import (`)
	fmt.Fprintln(&b, `	"github.com/spf13/cobra"`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `	"github.com/bronlabs/bron-cli/internal/body"`)
	fmt.Fprintln(&b, `	"github.com/bronlabs/bron-cli/internal/client"`)
	fmt.Fprintln(&b, `	"github.com/bronlabs/bron-cli/internal/output"`)
	fmt.Fprintln(&b, `	"github.com/bronlabs/bron-cli/internal/qparam"`)
	fmt.Fprintln(&b, `)`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// ClientProvider builds a configured client on demand.")
	fmt.Fprintln(&b, "type ClientProvider func() (*client.Client, error)")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Register attaches all generated subcommands to root.")
	fmt.Fprintln(&b, "func Register(root *cobra.Command, provide ClientProvider) {")

	for _, g := range groupByResource(plan) {
		emitResourceGroup(&b, g, "provide")
	}

	if len(shortcuts) > 0 {
		emitTxSubtree(&b, shortcuts, "provide")
	}

	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	emitHelpers(&b)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("gofmt: %w", err)
	}
	return formatted, nil
}

type resourceGroup struct {
	Name     string
	Commands []plannedCmd
}

func groupByResource(plan []plannedCmd) []resourceGroup {
	idx := map[string]int{}
	var groups []resourceGroup
	for _, c := range plan {
		i, ok := idx[c.Resource]
		if !ok {
			i = len(groups)
			idx[c.Resource] = i
			groups = append(groups, resourceGroup{Name: c.Resource})
		}
		groups[i].Commands = append(groups[i].Commands, c)
	}
	sort.Slice(groups, func(i, j int) bool { return groups[i].Name < groups[j].Name })
	return groups
}

func emitResourceGroup(b *bytes.Buffer, g resourceGroup, provideVar string) {
	fmt.Fprintln(b, "\t{")
	fmt.Fprintf(b, "\t\tres := &cobra.Command{Use: %q, Short: %q}\n", g.Name, "operations on "+g.Name)
	for _, c := range g.Commands {
		emitCommand(b, c, provideVar)
	}
	fmt.Fprintln(b, "\t\troot.AddCommand(res)")
	fmt.Fprintln(b, "\t}")
}

func emitCommand(b *bytes.Buffer, c plannedCmd, provideVar string) {
	fmt.Fprintln(b, "\t\t{")

	// Flag declarations.
	for _, q := range c.QueryParams {
		fmt.Fprintf(b, "\t\t\tvar q_%s string\n", goSafeIdent(q.Name))
	}
	for _, f := range c.BodyFields {
		fmt.Fprintf(b, "\t\t\tvar f_%s string\n", goSafeIdent(f))
	}
	if c.HasBody {
		fmt.Fprintln(b, "\t\t\tvar fileFlag string")
		fmt.Fprintln(b, "\t\t\tvar jsonFlag string")
	}

	// Cobra command.
	use := c.Verb
	for _, id := range c.PathArgs {
		use += " <" + id + ">"
	}
	fmt.Fprintln(b, "\t\t\tcmd := &cobra.Command{")
	fmt.Fprintf(b, "\t\t\t\tUse:   %q,\n", use)
	fmt.Fprintf(b, "\t\t\t\tShort: %q,\n", c.Method+" "+c.Path)
	if n := len(c.PathArgs); n > 0 {
		fmt.Fprintf(b, "\t\t\t\tArgs:  cobra.ExactArgs(%d),\n", n)
	}
	fmt.Fprintln(b, "\t\t\t\tRunE: func(cmd *cobra.Command, args []string) error {")
	fmt.Fprintf(b, "\t\t\t\t\tcli, err := %s()\n", provideVar)
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")

	// Path params.
	if len(c.PathArgs) > 0 {
		fmt.Fprintln(b, "\t\t\t\t\tpathParams := map[string]string{")
		for i, id := range c.PathArgs {
			fmt.Fprintf(b, "\t\t\t\t\t\t%q: args[%d],\n", id, i)
		}
		fmt.Fprintln(b, "\t\t\t\t\t}")
	} else {
		fmt.Fprintln(b, "\t\t\t\t\tvar pathParams map[string]string")
	}

	// Body.
	if c.HasBody {
		fmt.Fprintln(b, "\t\t\t\t\tbaseline, err := body.Parse(fileFlag, jsonFlag)")
		fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
		fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
		fmt.Fprintln(b, "\t\t\t\t\t}")
		if len(c.BodyFields) > 0 {
			fmt.Fprintln(b, "\t\t\t\t\tfields := map[string]string{")
			for _, f := range c.BodyFields {
				fmt.Fprintf(b, "\t\t\t\t\t\t%q: f_%s,\n", f, goSafeIdent(f))
			}
			fmt.Fprintln(b, "\t\t\t\t\t}")
		} else {
			fmt.Fprintln(b, "\t\t\t\t\tvar fields map[string]string")
		}
		fmt.Fprintln(b, "\t\t\t\t\tpayload, err := body.Compose(baseline, fields)")
		fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
		fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
		fmt.Fprintln(b, "\t\t\t\t\t}")
	} else {
		fmt.Fprintln(b, "\t\t\t\t\tvar payload interface{}")
	}

	// Query.
	if len(c.QueryParams) > 0 {
		fmt.Fprintln(b, "\t\t\t\t\tquery, err := compactQuery(map[string]interface{}{")
		for _, q := range c.QueryParams {
			fmt.Fprintf(b, "\t\t\t\t\t\t%q: q_%s,\n", q.Name, goSafeIdent(q.Name))
		}
		fmt.Fprintln(b, "\t\t\t\t\t})")
		fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
		fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
		fmt.Fprintln(b, "\t\t\t\t\t}")
	} else {
		fmt.Fprintln(b, "\t\t\t\t\tvar query interface{}")
	}

	fmt.Fprintln(b, "\t\t\t\t\tvar result interface{}")
	fmt.Fprintf(b, "\t\t\t\t\tif err := cli.Do(cmd.Context(), %q, %q, pathParams, payload, query, &result); err != nil {\n",
		c.Method, c.Path)
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\treturn output.Print(result)")
	fmt.Fprintln(b, "\t\t\t\t},")
	fmt.Fprintln(b, "\t\t\t}")

	// Flag bindings.
	for _, q := range c.QueryParams {
		fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&q_%s, %q, \"\", \"\")\n",
			goSafeIdent(q.Name), q.Name)
	}
	for _, f := range c.BodyFields {
		fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&f_%s, %q, \"\", \"\")\n",
			goSafeIdent(f), f)
	}
	if c.HasBody {
		fmt.Fprintln(b, `			cmd.Flags().StringVar(&fileFlag, "file", "", "read request body from file path ('-' for stdin)")`)
		fmt.Fprintln(b, `			cmd.Flags().StringVar(&jsonFlag, "json", "", "inline request body as a JSON string")`)
		fmt.Fprintln(b, `			cmd.MarkFlagsMutuallyExclusive("file", "json")`)
	}

	fmt.Fprintln(b, "\t\t\tres.AddCommand(cmd)")
	fmt.Fprintln(b, "\t\t}")
}

func emitTxSubtree(b *bytes.Buffer, shortcuts []txShortcut, provideVar string) {
	fmt.Fprintln(b, "\t{")
	fmt.Fprintln(b, `		tx := &cobra.Command{Use: "tx", Short: "create transaction (shortcut for transactions create --transactionType <type>)"}`)

	// `bron tx types` — list all known shortcut keys
	fmt.Fprintln(b, "\t\t{")
	fmt.Fprintln(b, "\t\t\ttypes := []string{")
	for _, s := range shortcuts {
		fmt.Fprintf(b, "\t\t\t\t%q,\n", s.Key)
	}
	fmt.Fprintln(b, "\t\t\t}")
	fmt.Fprintln(b, "\t\t\tcmd := &cobra.Command{")
	fmt.Fprintln(b, `				Use:   "types",`)
	fmt.Fprintln(b, `				Short: "list all transaction types",`)
	fmt.Fprintln(b, "\t\t\t\tRun: func(cmd *cobra.Command, args []string) {")
	fmt.Fprintln(b, "\t\t\t\t\tfor _, t := range types {")
	fmt.Fprintln(b, "\t\t\t\t\t\tcmd.Println(t)")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t},")
	fmt.Fprintln(b, "\t\t\t}")
	fmt.Fprintln(b, "\t\t\ttx.AddCommand(cmd)")
	fmt.Fprintln(b, "\t\t}")

	// One subcommand per type
	for _, s := range shortcuts {
		emitTxShortcut(b, s, provideVar)
	}

	fmt.Fprintln(b, "\t\troot.AddCommand(tx)")
	fmt.Fprintln(b, "\t}")
}

func emitTxShortcut(b *bytes.Buffer, s txShortcut, provideVar string) {
	fmt.Fprintln(b, "\t\t{")

	// Flag declarations.
	for _, f := range s.TopFields {
		fmt.Fprintf(b, "\t\t\tvar f_%s string\n", goSafeIdent(f))
	}
	for _, p := range s.Params {
		fmt.Fprintf(b, "\t\t\tvar p_%s string\n", goSafeIdent(p))
	}
	fmt.Fprintln(b, "\t\t\tvar fileFlag string")
	fmt.Fprintln(b, "\t\t\tvar jsonFlag string")

	fmt.Fprintln(b, "\t\t\tcmd := &cobra.Command{")
	fmt.Fprintf(b, "\t\t\t\tUse:   %q,\n", s.Key)
	fmt.Fprintf(b, "\t\t\t\tShort: %q,\n", "create "+s.Key+" transaction")
	fmt.Fprintln(b, "\t\t\t\tRunE: func(cmd *cobra.Command, args []string) error {")
	fmt.Fprintf(b, "\t\t\t\t\tcli, err := %s()\n", provideVar)
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tbaseline, err := body.Parse(fileFlag, jsonFlag)")
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tfields := map[string]string{")
	fmt.Fprintf(b, "\t\t\t\t\t\t\"transactionType\": %q,\n", s.Key)
	for _, f := range s.TopFields {
		fmt.Fprintf(b, "\t\t\t\t\t\t%q: f_%s,\n", f, goSafeIdent(f))
	}
	for _, p := range s.Params {
		fmt.Fprintf(b, "\t\t\t\t\t\t%q: p_%s,\n", "params."+p, goSafeIdent(p))
	}
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tpayload, err := body.Compose(baseline, fields)")
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tvar pathParams map[string]string")
	fmt.Fprintln(b, "\t\t\t\t\tvar query interface{}")
	fmt.Fprintln(b, "\t\t\t\t\tvar result interface{}")
	fmt.Fprintln(b, `					if err := cli.Do(cmd.Context(), "POST", "/workspaces/{workspaceId}/transactions", pathParams, payload, query, &result); err != nil {`)
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\treturn output.Print(result)")
	fmt.Fprintln(b, "\t\t\t\t},")
	fmt.Fprintln(b, "\t\t\t}")

	for _, f := range s.TopFields {
		fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&f_%s, %q, \"\", \"\")\n", goSafeIdent(f), f)
	}
	for _, p := range s.Params {
		fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&p_%s, %q, \"\", \"\")\n", goSafeIdent(p), "params."+p)
	}
	fmt.Fprintln(b, `			cmd.Flags().StringVar(&fileFlag, "file", "", "read request body from file path ('-' for stdin)")`)
	fmt.Fprintln(b, `			cmd.Flags().StringVar(&jsonFlag, "json", "", "inline request body as a JSON string")`)
	fmt.Fprintln(b, `			cmd.MarkFlagsMutuallyExclusive("file", "json")`)
	fmt.Fprintln(b, "\t\t\ttx.AddCommand(cmd)")
	fmt.Fprintln(b, "\t\t}")
}

func emitHelpers(b *bytes.Buffer) {
	fmt.Fprintln(b, `// compactQuery drops empty string values and coerces date-shaped parameters`)
	fmt.Fprintln(b, `// (createdAtFrom, updatedSince, ...) from ISO-8601 to epoch-millis if needed.`)
	fmt.Fprintln(b, `func compactQuery(m map[string]interface{}) (interface{}, error) {`)
	fmt.Fprintln(b, `	out := map[string]interface{}{}`)
	fmt.Fprintln(b, `	for k, v := range m {`)
	fmt.Fprintln(b, `		s, ok := v.(string)`)
	fmt.Fprintln(b, `		if !ok || s == "" {`)
	fmt.Fprintln(b, `			continue`)
	fmt.Fprintln(b, `		}`)
	fmt.Fprintln(b, `		coerced, err := qparam.MaybeDate(k, s)`)
	fmt.Fprintln(b, `		if err != nil {`)
	fmt.Fprintln(b, `			return nil, err`)
	fmt.Fprintln(b, `		}`)
	fmt.Fprintln(b, `		out[k] = coerced`)
	fmt.Fprintln(b, `	}`)
	fmt.Fprintln(b, `	if len(out) == 0 {`)
	fmt.Fprintln(b, `		return nil, nil`)
	fmt.Fprintln(b, `	}`)
	fmt.Fprintln(b, `	return out, nil`)
	fmt.Fprintln(b, `}`)
}

// emitHelpDoc generates a separate file with the static help map used by
// `bron schema` / `bron help-json` (and any future agent-mode commands).
func emitHelpDoc(plan []plannedCmd, shortcuts []txShortcut) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by cligen. DO NOT EDIT.")
	fmt.Fprintln(&b, "package generated")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type HelpEntry struct {")
	fmt.Fprintln(&b, "\tMethod      string")
	fmt.Fprintln(&b, "\tPath        string")
	fmt.Fprintln(&b, "\tBodyRef     string")
	fmt.Fprintln(&b, "\tResponseRef string")
	fmt.Fprintln(&b, "\tQueryParams []HelpQueryParam")
	fmt.Fprintln(&b, "\tPathArgs    []string")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type HelpQueryParam struct {")
	fmt.Fprintln(&b, "\tName     string")
	fmt.Fprintln(&b, "\tRequired bool")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type TxShortcut struct {")
	fmt.Fprintln(&b, "\tParamsRef string")
	fmt.Fprintln(&b, "\tParams    []string")
	fmt.Fprintln(&b, "\tTopFields []string")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "var HelpEntries = map[string]map[string]HelpEntry{")
	for _, g := range groupByResource(plan) {
		fmt.Fprintf(&b, "\t%q: {\n", g.Name)
		for _, c := range g.Commands {
			fmt.Fprintf(&b, "\t\t%q: {Method: %q, Path: %q, BodyRef: %q, ResponseRef: %q",
				c.Verb, c.Method, c.Path, c.BodyRef, c.ResponseRef)
			if len(c.PathArgs) > 0 {
				fmt.Fprint(&b, ", PathArgs: []string{")
				for i, a := range c.PathArgs {
					if i > 0 {
						fmt.Fprint(&b, ", ")
					}
					fmt.Fprintf(&b, "%q", a)
				}
				fmt.Fprint(&b, "}")
			}
			if len(c.QueryParams) > 0 {
				fmt.Fprint(&b, ", QueryParams: []HelpQueryParam{")
				for i, q := range c.QueryParams {
					if i > 0 {
						fmt.Fprint(&b, ", ")
					}
					fmt.Fprintf(&b, "{Name: %q, Required: %t}", q.Name, q.Required)
				}
				fmt.Fprint(&b, "}")
			}
			fmt.Fprintln(&b, "},")
		}
		fmt.Fprintln(&b, "\t},")
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "var TxShortcuts = map[string]TxShortcut{")
	for _, s := range shortcuts {
		fmt.Fprintf(&b, "\t%q: {ParamsRef: %q, ", s.Key, s.Class)
		fmt.Fprint(&b, "Params: []string{")
		for i, p := range s.Params {
			if i > 0 {
				fmt.Fprint(&b, ", ")
			}
			fmt.Fprintf(&b, "%q", p)
		}
		fmt.Fprint(&b, "}, TopFields: []string{")
		for i, f := range s.TopFields {
			if i > 0 {
				fmt.Fprint(&b, ", ")
			}
			fmt.Fprintf(&b, "%q", f)
		}
		fmt.Fprintln(&b, "}},")
	}
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("gofmt helpdoc: %w", err)
	}
	return formatted, nil
}

// goSafeIdent converts a string into a Go-safe identifier suffix.
// Keeps alphanumerics, replaces other runes with underscore.
func goSafeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	if b.Len() == 0 {
		return "_"
	}
	return b.String()
}
