// cligen reads bron-open-api-public.json and emits cobra command definitions
// under generated/. Resources come from OpenAPI tags (kebab-case), verbs are
// derived from the HTTP method + URL shape: GET /xxx → list, GET /xxx/{id} →
// get, POST → create, PUT/PATCH → update, DELETE → delete. Trailing path
// segments after an id become the verb (POST /xxx/{id}/yyy → yyy). Names map
// 1:1 with the spec — no aliases, no remapping — so the spec stays the source
// of truth and the CLI regenerates losslessly on every release.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// resourceAliases — short/disambiguated CLI names for select URL segments.
var resourceAliases = map[string]string{
	"address-book-records": "address-book",
	"addresses":            "deposit-addresses",
	"transactions":         "tx",
}

// endpointAliases — full (method,path) overrides for endpoints that logically
// belong under a different resource.
var endpointAliases = map[string]string{
	"GET /dictionary/asset-market-prices":  "assets prices",
	"GET /dictionary/symbol-market-prices": "symbols prices",
}

// httpMethods — keys under an OpenAPI path item that represent operations.
var httpMethods = map[string]struct{}{
	"get": {}, "post": {}, "put": {}, "patch": {},
	"delete": {}, "options": {}, "head": {}, "trace": {},
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: cligen <openapi.json> [out-dir]")
		os.Exit(2)
	}
	specPath := os.Args[1]
	outDir := "generated"
	if len(os.Args) >= 3 {
		outDir = os.Args[2]
	}

	data, err := os.ReadFile(specPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "read spec:", err)
		os.Exit(1)
	}

	var spec rawSpec
	if err := json.Unmarshal(data, &spec); err != nil {
		fmt.Fprintln(os.Stderr, "parse spec:", err)
		os.Exit(1)
	}

	plan, err := buildPlan(spec)
	if err != nil {
		fmt.Fprintln(os.Stderr, "build plan:", err)
		os.Exit(1)
	}
	sort.Slice(plan, func(i, j int) bool {
		if plan[i].Resource != plan[j].Resource {
			return plan[i].Resource < plan[j].Resource
		}
		return plan[i].Verb < plan[j].Verb
	})

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mkdir out:", err)
		os.Exit(1)
	}
	shortcuts := collectTxShortcuts(spec)
	src, err := emit(plan, shortcuts)
	if err != nil {
		fmt.Fprintln(os.Stderr, "emit:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(outDir, "commands.go"), src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write commands.go:", err)
		os.Exit(1)
	}

	// helpdoc.go — HelpEntries map used by `bron schema` / `bron help-json`
	helpSrc, err := emitHelpDoc(plan, shortcuts)
	if err != nil {
		fmt.Fprintln(os.Stderr, "emit helpdoc:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(outDir, "helpdoc.go"), helpSrc, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write helpdoc.go:", err)
		os.Exit(1)
	}

	// spec.go + spec.json — embedded raw OpenAPI for schema lookup at runtime
	if err := os.WriteFile(filepath.Join(outDir, "spec.json"), data, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write spec.json:", err)
		os.Exit(1)
	}
	specSrc := []byte(`// Code generated by cligen. DO NOT EDIT.
package generated

import _ "embed"

//go:embed spec.json
var Spec []byte
`)
	if err := os.WriteFile(filepath.Join(outDir, "spec.go"), specSrc, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write spec.go:", err)
		os.Exit(1)
	}

	fmt.Printf("generated %s/{commands,helpdoc,spec}.go (%d endpoints, %d tx-types)\n", outDir, len(plan), len(shortcuts))
}

// --- tx <type> shortcuts ---

type txShortcut struct {
	Key       string      // "withdrawal", "stake-delegation"
	Class     string      // "WithdrawalParams"
	TopFields []bodyField // CreateTransaction top-level fields except transactionType and params
	Params    []bodyField // leaves under "params." (without prefix)
}

// txKeyOverrides handles class→key mismatches the kebab-case derivation
// can't infer (e.g. "StakeUnDelegationParams" — the embedded "Un" capitals
// would split into "stake-un-delegation" instead of "stake-undelegation").
// Keep tiny; only add when a transactionType enum value disagrees with what
// classToKey would produce.
var txKeyOverrides = map[string]string{
	"StakeUnDelegationParams": "stake-undelegation",
}

// reservedTxNames are hand-written children of `bron tx` that live in
// cmd/bron/main.go (e.g. `bron tx subscribe`). Listed here so the conflict
// guard fails generation if a future transactionType key collides with one.
var reservedTxNames = []string{"subscribe"}

// reservedEmbedTokens are hand-wired CLI-side `--embed` orchestrators in
// cmd/bron/{balances_prices,tx_assets}.go. If the spec ever exposes an
// includeXxx query param that camelises to one of these tokens, generation
// fails — applyEmbed would otherwise route the same token through both the
// orchestrator and the generated --includeXxx flag, double-firing.
//
// Each entry is the (resource, verb, token) triple the orchestrator owns.
var reservedEmbedTokens = []struct{ resource, verb, token string }{
	{"balances", "list", "prices"},
	{"tx", "list", "assets"},
}

func collectTxShortcuts(spec rawSpec) []txShortcut {
	reg := spec.Components.Schemas
	create, ok := reg["CreateTransaction"]
	if !ok {
		return nil
	}

	// Authoritative list of valid transactionType values (from the enum schema).
	// Shortcuts are only emitted for keys present in this set, so we never produce
	// a `bron tx <type>` that the API would reject.
	validTypes := map[string]bool{}
	if tt, ok := reg["TransactionType"]; ok {
		for _, v := range tt.Enum {
			if s, ok := v.(string); ok {
				validTypes[s] = true
			}
		}
	}

	// Collect top-level fields that are scalars/arrays — skip transactionType (fixed by shortcut)
	// and skip params (handled per shortcut below).
	var topFields []bodyField
	for name, prop := range create.Properties {
		if name == "transactionType" || name == "params" {
			continue
		}
		switch propKind(prop, reg) {
		case "scalar":
			t, f := leafTypeFormat(prop, reg)
			topFields = append(topFields, bodyField{DotPath: name, Type: t, Format: f, Description: strings.TrimSpace(prop.Description), Enum: enumValues(prop, reg)})
		case "array":
			t, f := arrayItemTypeFormat(prop, reg)
			topFields = append(topFields, bodyField{DotPath: name, Type: t + "[]", Format: f, Description: strings.TrimSpace(prop.Description), Enum: enumValues(prop, reg)})
		}
	}
	sort.Slice(topFields, func(i, j int) bool { return topFields[i].DotPath < topFields[j].DotPath })

	paramsProp, ok := create.Properties["params"]
	if !ok || len(paramsProp.OneOf) == 0 {
		return nil
	}

	seen := map[string]bool{}
	var out []txShortcut
	for _, p := range paramsProp.OneOf {
		if p.Ref == "" {
			continue
		}
		cls := refName(p.Ref)
		if seen[cls] {
			continue
		}
		seen[cls] = true

		key, ok := txKeyOverrides[cls]
		if !ok {
			key = classToKey(cls)
		}
		// Skip Params classes whose derived key isn't a real transactionType.
		// Avoids exposing dead `bron tx <type>` commands the API would reject.
		if len(validTypes) > 0 && !validTypes[key] {
			continue
		}

		out = append(out, txShortcut{
			Key:       key,
			Class:     cls,
			TopFields: topFields,
			Params:    collectLeaves(p, "", reg),
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Key < out[j].Key })
	return out
}

// classToKey converts a Params class name to its kebab-case TransactionType key.
// "WithdrawalParams" → "withdrawal"; "StakeDelegationParams" → "stake-delegation".
func classToKey(cls string) string {
	s := strings.TrimSuffix(cls, "Params")
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('-')
			}
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// --- spec types ---

type rawSpec struct {
	Paths      map[string]map[string]json.RawMessage `json:"paths"`
	Components struct {
		Schemas map[string]rawSchema `json:"schemas"`
	} `json:"components"`
}

type rawOp struct {
	Summary     string                 `json:"summary"`
	Description string                 `json:"description"`
	Tags        []string               `json:"tags"`
	Parameters  []rawParam             `json:"parameters"`
	RequestBody *rawReqBody            `json:"requestBody"`
	Responses   map[string]rawResponse `json:"responses"`
}

type rawResponse struct {
	Content map[string]rawContent `json:"content"`
}

type rawParam struct {
	Name        string     `json:"name"`
	In          string     `json:"in"`
	Required    bool       `json:"required"`
	Description string     `json:"description"`
	Schema      *rawSchema `json:"schema"`
}

type rawReqBody struct {
	Content map[string]rawContent `json:"content"`
}

type rawContent struct {
	Schema rawSchema `json:"schema"`
}

type rawSchema struct {
	Type        string               `json:"type"`
	Format      string               `json:"format"`
	Description string               `json:"description"`
	Ref         string               `json:"$ref"`
	Properties  map[string]rawSchema `json:"properties"`
	Required    []string             `json:"required"`
	Items       *rawSchema           `json:"items"`
	OneOf       []rawSchema          `json:"oneOf"`
	AnyOf       []rawSchema          `json:"anyOf"`
	AllOf       []rawSchema          `json:"allOf"`
	Enum        []interface{}        `json:"enum"`
}

// --- planning ---

type plannedCmd struct {
	Method      string
	Path        string
	Resource    string
	Verb        string
	Summary     string   // OpenAPI operation.summary, used as the cobra Short description
	PathArgs    []string // names from URL placeholders, in order
	QueryParams []param
	BodyFields  []bodyField // leaves of the request body schema (skips oneOf)
	HasBody     bool
	BodyRef     string   // component name of request body schema (e.g. "CreateTransaction")
	ResponseRef string   // component name of 200/201 response schema (e.g. "Transactions")
	Permissions []string // API key permissions allowed for this endpoint, e.g. ["View only", "Transaction Operator"]
}

// embedTokens picks the includeXxx query params and converts them to the
// kebab-case tokens accepted by the global `--embed` flag — gives the help
// renderer the per-command list of valid embed values without re-walking the
// raw query params at runtime.
func (c plannedCmd) embedTokens() []string {
	var out []string
	for _, q := range c.QueryParams {
		tok, ok := embedTokenFromInclude(q.Name)
		if !ok {
			continue
		}
		out = append(out, tok)
	}
	sort.Strings(out)
	return out
}

// parsePermissions extracts the API-key permission set from the operation
// description. The OpenAPI generator macro on the backend appends a line
// like `<sup>API Key permissions: View only, Transaction Operator, Full Access</sup>`
// to the description; we mine that line so the MCP server can use it as
// the source of truth for `--read-only` filtering (a tool ships in read-only
// mode iff its permission set is exactly {"View only"}).
//
// Returns nil if the description doesn't carry the marker — for endpoints
// without explicit permissions we treat them as state-changing (fail-safe).
var permissionsRe = regexp.MustCompile(`(?i)API Key permissions:\s*([^<\n]+)`)

func parsePermissions(description string) []string {
	m := permissionsRe.FindStringSubmatch(description)
	if len(m) < 2 {
		return nil
	}
	out := make([]string, 0, 4)
	for _, p := range strings.Split(m[1], ",") {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

func embedTokenFromInclude(flag string) (string, bool) {
	const prefix = "include"
	if !strings.HasPrefix(flag, prefix) || len(flag) == len(prefix) {
		return "", false
	}
	rest := flag[len(prefix):]
	if rest[0] < 'A' || rest[0] > 'Z' {
		return "", false
	}
	var b strings.Builder
	for i, r := range rest {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('-')
			}
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String(), true
}

type param struct {
	Name        string
	Required    bool
	Type        string // OpenAPI type: "string" | "integer" | "boolean" | "array"
	Format      string // OpenAPI format: "int64" | "date-time-millis" | "decimal" | ...
	Description string
	Enum        []string // resolved enum values (for arrays: from items)
}

// bodyField is a body-schema leaf carrying its OpenAPI type/format/description.
// Type info drives the cobra flag's help string so users see the underlying shape
// (`[int64]`, `[date-time-millis]`, `[decimal]`) instead of a bare `string`.
type bodyField struct {
	DotPath     string
	Type        string
	Format      string
	Description string
	Enum        []string
}

func buildPlan(spec rawSpec) ([]plannedCmd, error) {
	registry := spec.Components.Schemas

	var out []plannedCmd
	for route, methods := range spec.Paths {
		for key, raw := range methods {
			if _, ok := httpMethods[strings.ToLower(key)]; !ok {
				continue
			}
			var op rawOp
			if err := json.Unmarshal(raw, &op); err != nil {
				return nil, fmt.Errorf("path %q method %q: %w", route, key, err)
			}
			method := strings.ToUpper(key)
			cmd := derive(method, route)
			cmd.Summary = strings.TrimSpace(op.Summary)
			cmd.Permissions = parsePermissions(op.Description)
			for _, p := range op.Parameters {
				if p.In == "query" {
					qp := param{Name: p.Name, Required: p.Required, Description: strings.TrimSpace(p.Description)}
					if p.Schema != nil {
						qp.Type = p.Schema.Type
						qp.Format = p.Schema.Format
						if qp.Type == "array" && p.Schema.Items != nil && p.Schema.Items.Type != "" {
							qp.Type = p.Schema.Items.Type + "[]"
							if p.Schema.Items.Format != "" {
								qp.Format = p.Schema.Items.Format
							}
						}
						qp.Enum = enumValues(*p.Schema, registry)
					}
					cmd.QueryParams = append(cmd.QueryParams, qp)
				}
			}
			if op.RequestBody != nil {
				cmd.HasBody = true
				if jc, ok := op.RequestBody.Content["application/json"]; ok {
					cmd.BodyFields = collectLeaves(jc.Schema, "", registry)
					if jc.Schema.Ref != "" {
						cmd.BodyRef = refName(jc.Schema.Ref)
					}
				}
			}
			for _, code := range []string{"200", "201"} {
				if resp, ok := op.Responses[code]; ok {
					if jc, ok := resp.Content["application/json"]; ok && jc.Schema.Ref != "" {
						cmd.ResponseRef = refName(jc.Schema.Ref)
						break
					}
				}
			}
			out = append(out, cmd)
		}
	}
	return out, nil
}

// derive turns an (HTTP method, URL path) pair into a (resource, verb,
// pathArgs) triple. URL placeholders become arg names; trailing non-placeholder
// segments after an id become the verb. resourceAliases / endpointAliases
// override specific cases that don't read well from the URL alone.
func derive(method, path string) plannedCmd {
	if alias, ok := endpointAliases[method+" "+path]; ok {
		_, args := splitPath(path)
		return plannedCmd{Method: method, Path: path, Resource: firstWord(alias), Verb: tail(alias), PathArgs: args}
	}

	stripped := stripPrefix(path)
	segments := splitSegments(stripped)

	if len(segments) == 0 {
		return plannedCmd{Method: method, Path: path, Resource: "workspace", Verb: "info"}
	}

	resource := segments[0]
	if alias, ok := resourceAliases[resource]; ok {
		resource = alias
	}

	tailSeg := segments[1:]
	var ids []string
	var verbParts []string
	for _, s := range tailSeg {
		if isPlaceholder(s) {
			ids = append(ids, strings.TrimSuffix(strings.TrimPrefix(s, "{"), "}"))
		} else {
			verbParts = append(verbParts, s)
		}
	}

	verb := strings.Join(verbParts, " ")
	if verb == "" {
		switch method {
		case "GET":
			if len(ids) == 0 {
				verb = "list"
			} else {
				verb = "get"
			}
		case "POST":
			verb = "create"
		case "PUT", "PATCH":
			verb = "update"
		case "DELETE":
			verb = "delete"
		default:
			verb = strings.ToLower(method)
		}
	}
	return plannedCmd{Method: method, Path: path, Resource: resource, Verb: verb, PathArgs: ids}
}

var stripPrefixes = []string{"/workspaces/{workspaceId}", "/dictionary"}

func stripPrefix(p string) string {
	for _, pref := range stripPrefixes {
		if strings.HasPrefix(p, pref) {
			return strings.TrimPrefix(p, pref)
		}
	}
	return p
}

func splitSegments(p string) []string {
	parts := strings.Split(p, "/")
	out := parts[:0]
	for _, x := range parts {
		if x != "" {
			out = append(out, x)
		}
	}
	return out
}

func splitPath(p string) (string, []string) {
	stripped := stripPrefix(p)
	segs := splitSegments(stripped)
	var ids []string
	for _, s := range segs {
		if isPlaceholder(s) {
			ids = append(ids, strings.TrimSuffix(strings.TrimPrefix(s, "{"), "}"))
		}
	}
	return stripped, ids
}

func isPlaceholder(s string) bool {
	return len(s) >= 2 && s[0] == '{' && s[len(s)-1] == '}'
}

func firstWord(s string) string {
	i := strings.IndexByte(s, ' ')
	if i < 0 {
		return s
	}
	return s[:i]
}

func tail(s string) string {
	i := strings.IndexByte(s, ' ')
	if i < 0 {
		return ""
	}
	return s[i+1:]
}

// --- schema walking ---

// collectLeaves returns every scalar/array leaf reachable from schema, with the
// dot-path plus the leaf's OpenAPI type/format/description. Refs are resolved via
// registry. oneOf/anyOf branches are skipped (no discriminator, can't pick a
// shape). allOf is treated as union of properties.
func collectLeaves(s rawSchema, prefix string, reg map[string]rawSchema) []bodyField {
	var out []bodyField
	visited := map[string]bool{}
	walkLeaves(s, prefix, reg, visited, &out)
	sort.Slice(out, func(i, j int) bool { return out[i].DotPath < out[j].DotPath })
	return out
}

func walkLeaves(s rawSchema, prefix string, reg map[string]rawSchema, visited map[string]bool, out *[]bodyField) {
	if s.Ref != "" {
		name := refName(s.Ref)
		if visited[name] {
			return
		}
		visited[name] = true
		defer delete(visited, name)
		s = reg[name]
	}
	if len(s.OneOf) > 0 || len(s.AnyOf) > 0 {
		return
	}
	for _, child := range s.AllOf {
		walkLeaves(child, prefix, reg, visited, out)
	}
	for name, prop := range s.Properties {
		dot := name
		if prefix != "" {
			dot = prefix + "." + name
		}
		switch propKind(prop, reg) {
		case "scalar":
			t, f := leafTypeFormat(prop, reg)
			*out = append(*out, bodyField{DotPath: dot, Type: t, Format: f, Description: strings.TrimSpace(prop.Description), Enum: enumValues(prop, reg)})
		case "array":
			t, f := arrayItemTypeFormat(prop, reg)
			*out = append(*out, bodyField{DotPath: dot, Type: t + "[]", Format: f, Description: strings.TrimSpace(prop.Description), Enum: enumValues(prop, reg)})
		case "object":
			walkLeaves(prop, dot, reg, visited, out)
		}
	}
}

// leafTypeFormat resolves a scalar property's (type, format), following $ref to
// pick up the underlying primitive (e.g. enum schemas surface as `string`).
func leafTypeFormat(s rawSchema, reg map[string]rawSchema) (string, string) {
	if s.Ref != "" {
		ref := reg[refName(s.Ref)]
		t := ref.Type
		if t == "" {
			t = "string"
		}
		return t, ref.Format
	}
	t := s.Type
	if t == "" {
		t = "string"
	}
	return t, s.Format
}

// arrayItemTypeFormat extracts the (item-type, item-format) for an array prop.
func arrayItemTypeFormat(s rawSchema, reg map[string]rawSchema) (string, string) {
	if s.Items == nil {
		return "string", ""
	}
	return leafTypeFormat(*s.Items, reg)
}

func propKind(s rawSchema, reg map[string]rawSchema) string {
	if s.Ref != "" {
		s = reg[refName(s.Ref)]
	}
	if len(s.OneOf) > 0 || len(s.AnyOf) > 0 {
		return "skip"
	}
	switch s.Type {
	case "string", "integer", "number", "boolean":
		return "scalar"
	case "array":
		return "array"
	case "object":
		return "object"
	}
	if len(s.Properties) > 0 {
		return "object"
	}
	return "scalar" // unknown → treat as scalar so user can still set it via --flag
}

func refName(ref string) string {
	parts := strings.Split(ref, "/")
	return parts[len(parts)-1]
}

// enumValues returns the enum string values reachable from s.
//
// For arrays, the enum lives on the items schema. For scalars, it may be
// inline (s.Enum) or behind a $ref to a named enum schema. Anything that
// resolves to non-string enum values is dropped — flag help only renders
// strings.
func enumValues(s rawSchema, reg map[string]rawSchema) []string {
	if s.Type == "array" && s.Items != nil {
		return enumValues(*s.Items, reg)
	}
	values := s.Enum
	if len(values) == 0 && s.Ref != "" {
		values = reg[refName(s.Ref)].Enum
	}
	if len(values) == 0 {
		return nil
	}
	out := make([]string, 0, len(values))
	for _, v := range values {
		if str, ok := v.(string); ok {
			out = append(out, str)
		}
	}
	return out
}

// seeDetailsLink matches the redundant `[See details](/enums/Foo)` markdown
// suffix that the spec attaches to enum-typed parameters. Stripped from the
// CLI help text once we inline the actual enum values.
var seeDetailsLink = regexp.MustCompile(`\s*\[See details\]\([^)]*\)\s*\.?\s*$`)

// --- emission ---

func emit(plan []plannedCmd, shortcuts []txShortcut) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintln(&b, "// Code generated by cligen. DO NOT EDIT.")
	fmt.Fprintln(&b, "package generated")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `import (`)
	fmt.Fprintln(&b, `	"fmt"`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `	"github.com/spf13/cobra"`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `	"github.com/bronlabs/bron-cli/internal/body"`)
	fmt.Fprintln(&b, `	"github.com/bronlabs/bron-cli/internal/client"`)
	fmt.Fprintln(&b, `	"github.com/bronlabs/bron-cli/internal/output"`)
	fmt.Fprintln(&b, `	"github.com/bronlabs/bron-cli/internal/qparam"`)
	fmt.Fprintln(&b, `)`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// ClientProvider builds a configured client on demand.")
	fmt.Fprintln(&b, "type ClientProvider func() (*client.Client, error)")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Register attaches all generated subcommands to root.")
	fmt.Fprintln(&b, "func Register(root *cobra.Command, provide ClientProvider) {")

	// Conflict guard: every tx-shortcut key must be distinct from every
	// `bron tx <verb>` name AND every hand-written `tx <name>` child registered
	// in cmd/bron/main.go. They all live under the same parent now (no separate
	// `bron transactions` root), so a future spec change adding a transactionType
	// called "list" or "subscribe" must fail at gen time.
	verbsByResource := map[string]map[string]bool{}
	for _, c := range plan {
		if verbsByResource[c.Resource] == nil {
			verbsByResource[c.Resource] = map[string]bool{}
		}
		verbsByResource[c.Resource][c.Verb] = true
	}
	for _, name := range reservedTxNames {
		if verbsByResource["tx"] == nil {
			verbsByResource["tx"] = map[string]bool{}
		}
		verbsByResource["tx"][name] = true
	}
	for _, s := range shortcuts {
		if verbsByResource["tx"][s.Key] {
			return nil, fmt.Errorf("transactionType %q collides with `bron tx %s` verb — pick a different transactionType key or rename the verb", s.Key, s.Key)
		}
	}

	// Guard against backend adding an includeXxx query param that camelises to
	// the same kebab token as a hand-wired embed orchestrator. Two paths
	// claiming the same token would silently double-fire at runtime.
	for _, rsv := range reservedEmbedTokens {
		for _, c := range plan {
			if c.Resource != rsv.resource || c.Verb != rsv.verb {
				continue
			}
			for _, q := range c.QueryParams {
				if tok, ok := embedTokenFromInclude(q.Name); ok && tok == rsv.token {
					return nil, fmt.Errorf("query param --%s on `bron %s %s` camelises to embed token %q which is hand-wired in cmd/bron/ — drop the orchestrator or rename one of the two",
						q.Name, rsv.resource, rsv.verb, rsv.token)
				}
			}
		}
	}

	for _, g := range groupByResource(plan) {
		if g.Name == "tx" {
			emitResourceGroup(&b, g, "provide", shortcuts)
		} else {
			emitResourceGroup(&b, g, "provide", nil)
		}
	}

	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	emitHelpers(&b)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("gofmt: %w", err)
	}
	return formatted, nil
}

type resourceGroup struct {
	Name     string
	Commands []plannedCmd
}

func groupByResource(plan []plannedCmd) []resourceGroup {
	idx := map[string]int{}
	var groups []resourceGroup
	for _, c := range plan {
		i, ok := idx[c.Resource]
		if !ok {
			i = len(groups)
			idx[c.Resource] = i
			groups = append(groups, resourceGroup{Name: c.Resource})
		}
		groups[i].Commands = append(groups[i].Commands, c)
	}
	sort.Slice(groups, func(i, j int) bool { return groups[i].Name < groups[j].Name })
	return groups
}

func emitResourceGroup(b *bytes.Buffer, g resourceGroup, provideVar string, shortcuts []txShortcut) {
	verbs := make([]string, len(g.Commands))
	hasList := false
	for i, c := range g.Commands {
		verbs[i] = c.Verb
		if c.Verb == "list" {
			hasList = true
		}
	}
	// zsh completion groups commands that share the same Short into a
	// single row, so always include the resource name to keep them
	// unique — "get, list — balances" vs "get, list — accounts".
	short := strings.Join(verbs, ", ") + " — " + g.Name
	if len(shortcuts) > 0 {
		short += "; create-shortcut: " + strings.Join(shortcutKeys(shortcuts), ", ")
	}
	fmt.Fprintln(b, "\t{")
	fmt.Fprintf(b, "\t\tres := &cobra.Command{Use: %q, Short: %q, GroupID: \"api\"}\n", g.Name, short)
	for _, c := range g.Commands {
		emitCommand(b, c, provideVar)
	}
	// For `tx`, also fold in the per-transactionType create shortcuts so the
	// command is one mental space — `bron tx list`, `bron tx withdrawal`, ...
	for _, s := range shortcuts {
		emitTxShortcut(b, s, provideVar)
	}

	// And mirror the same shortcuts under `bron tx dry-run <type>` — same flat
	// `--params.*` flags as `bron tx <type>`, but POSTs to /transactions/dry-run.
	// Attaches as children of the existing generated `dry-run` command, so
	// `bron tx dry-run --transactionType … --json …` keeps working unchanged.
	if len(shortcuts) > 0 {
		fmt.Fprintln(b, "\t\tvar dryRunCmd *cobra.Command")
		fmt.Fprintln(b, "\t\tfor _, c := range res.Commands() {")
		fmt.Fprintln(b, "\t\t\tif c.Name() == \"dry-run\" {")
		fmt.Fprintln(b, "\t\t\t\tdryRunCmd = c")
		fmt.Fprintln(b, "\t\t\t\tbreak")
		fmt.Fprintln(b, "\t\t\t}")
		fmt.Fprintln(b, "\t\t}")
		fmt.Fprintln(b, "\t\tif dryRunCmd != nil {")
		for _, s := range shortcuts {
			emitTxDryRunShortcut(b, s, provideVar)
		}
		fmt.Fprintln(b, "\t\t}")
	}

	// `bron <resource>` with no verb: default to `list` if available, otherwise
	// emit an error pointing at the available actions.
	if hasList {
		fmt.Fprintln(b, "\t\tfor _, c := range res.Commands() {")
		fmt.Fprintln(b, "\t\t\tif c.Name() == \"list\" {")
		fmt.Fprintln(b, "\t\t\t\tres.RunE = c.RunE")
		fmt.Fprintln(b, "\t\t\t\tres.Args = c.Args")
		fmt.Fprintln(b, "\t\t\t\tres.Flags().AddFlagSet(c.Flags())")
		fmt.Fprintln(b, "\t\t\t\tbreak")
		fmt.Fprintln(b, "\t\t\t}")
		fmt.Fprintln(b, "\t\t}")
	} else {
		fmt.Fprintln(b, "\t\tres.RunE = func(cmd *cobra.Command, args []string) error {")
		fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"specify an action: %s (available: %s)\")\n",
			g.Name, strings.Join(verbs, ", "))
		fmt.Fprintln(b, "\t\t}")
	}

	fmt.Fprintln(b, "\t\troot.AddCommand(res)")
	fmt.Fprintln(b, "\t}")
}

func shortcutKeys(s []txShortcut) []string {
	keys := make([]string, len(s))
	for i, sc := range s {
		keys[i] = sc.Key
	}
	return keys
}

func emitCommand(b *bytes.Buffer, c plannedCmd, provideVar string) {
	fmt.Fprintln(b, "\t\t{")

	// Flag declarations.
	for _, q := range c.QueryParams {
		fmt.Fprintf(b, "\t\t\tvar q_%s string\n", goSafeIdent(q.Name))
	}
	for _, f := range c.BodyFields {
		fmt.Fprintf(b, "\t\t\tvar f_%s string\n", goSafeIdent(f.DotPath))
	}
	if c.HasBody {
		fmt.Fprintln(b, "\t\t\tvar fileFlag string")
		fmt.Fprintln(b, "\t\t\tvar jsonFlag string")
	}

	// Cobra command.
	use := c.Verb
	for _, id := range c.PathArgs {
		use += " <" + id + ">"
	}
	short := c.Summary
	if short == "" {
		short = c.Method
	}
	fmt.Fprintln(b, "\t\t\tcmd := &cobra.Command{")
	fmt.Fprintf(b, "\t\t\t\tUse:   %q,\n", use)
	fmt.Fprintf(b, "\t\t\t\tShort: %q,\n", short)
	if n := len(c.PathArgs); n > 0 {
		fmt.Fprintf(b, "\t\t\t\tArgs:  cobra.ExactArgs(%d),\n", n)
	}
	fmt.Fprintln(b, "\t\t\t\tRunE: func(cmd *cobra.Command, args []string) error {")
	fmt.Fprintf(b, "\t\t\t\t\tcli, err := %s()\n", provideVar)
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")

	// Path params.
	if len(c.PathArgs) > 0 {
		fmt.Fprintln(b, "\t\t\t\t\tpathParams := map[string]string{")
		for i, id := range c.PathArgs {
			fmt.Fprintf(b, "\t\t\t\t\t\t%q: args[%d],\n", id, i)
		}
		fmt.Fprintln(b, "\t\t\t\t\t}")
	} else {
		fmt.Fprintln(b, "\t\t\t\t\tvar pathParams map[string]string")
	}

	// Body.
	if c.HasBody {
		fmt.Fprintln(b, "\t\t\t\t\tbaseline, err := body.Parse(fileFlag, jsonFlag)")
		fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
		fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
		fmt.Fprintln(b, "\t\t\t\t\t}")
		if len(c.BodyFields) > 0 {
			fmt.Fprintln(b, "\t\t\t\t\tfields := map[string]string{")
			for _, f := range c.BodyFields {
				fmt.Fprintf(b, "\t\t\t\t\t\t%q: f_%s,\n", f.DotPath, goSafeIdent(f.DotPath))
			}
			fmt.Fprintln(b, "\t\t\t\t\t}")
		} else {
			fmt.Fprintln(b, "\t\t\t\t\tvar fields map[string]string")
		}
		fmt.Fprintln(b, "\t\t\t\t\tpayload, err := body.Compose(baseline, fields)")
		fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
		fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
		fmt.Fprintln(b, "\t\t\t\t\t}")
		fmt.Fprintln(b, "\t\t\t\t\tif err := qparam.CoerceBodyDates(payload); err != nil {")
		fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
		fmt.Fprintln(b, "\t\t\t\t\t}")
	} else {
		fmt.Fprintln(b, "\t\t\t\t\tvar payload interface{}")
	}

	// Query.
	if len(c.QueryParams) > 0 {
		// Validate enum-typed query params on the CLI side before hitting the
		// wire. The backend silently ignores unknown enum values on list
		// endpoints (returns an empty page), which is unhelpful for humans
		// and agents alike — fail fast with the allowed list.
		for _, q := range c.QueryParams {
			if len(q.Enum) == 0 {
				continue
			}
			// Treat both `string[]` (resolved item type) and bare `array` (item
			// is an unresolved $ref to an enum schema) as repeating params.
			repeat := strings.HasSuffix(q.Type, "[]") || q.Type == "array"
			fmt.Fprintf(b, "\t\t\t\t\tif err := qparam.ValidateEnum(%q, q_%s, []string{",
				q.Name, goSafeIdent(q.Name))
			for i, v := range q.Enum {
				if i > 0 {
					fmt.Fprint(b, ", ")
				}
				fmt.Fprintf(b, "%q", v)
			}
			fmt.Fprintf(b, "}, %t); err != nil {\n", repeat)
			fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
			fmt.Fprintln(b, "\t\t\t\t\t}")
		}
		fmt.Fprintln(b, "\t\t\t\t\tquery, err := compactQuery(map[string]interface{}{")
		for _, q := range c.QueryParams {
			fmt.Fprintf(b, "\t\t\t\t\t\t%q: q_%s,\n", q.Name, goSafeIdent(q.Name))
		}
		fmt.Fprintln(b, "\t\t\t\t\t})")
		fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
		fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
		fmt.Fprintln(b, "\t\t\t\t\t}")
	} else {
		fmt.Fprintln(b, "\t\t\t\t\tvar query interface{}")
	}

	fmt.Fprintln(b, "\t\t\t\t\tvar result interface{}")
	fmt.Fprintf(b, "\t\t\t\t\tif err := cli.Do(cmd.Context(), %q, %q, pathParams, payload, query, &result); err != nil {\n",
		c.Method, c.Path)
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\treturn output.Print(result)")
	fmt.Fprintln(b, "\t\t\t\t},")
	fmt.Fprintln(b, "\t\t\t}")

	// Flag bindings.
	for _, q := range c.QueryParams {
		fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&q_%s, %q, \"\", %q)\n",
			goSafeIdent(q.Name), q.Name, flagHelp(q.Type, q.Format, q.Description, q.Enum, q.Required))
	}
	for _, f := range c.BodyFields {
		fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&f_%s, %q, \"\", %q)\n",
			goSafeIdent(f.DotPath), f.DotPath, flagHelp(f.Type, f.Format, f.Description, f.Enum, false))
	}
	if c.HasBody {
		fmt.Fprintln(b, `			cmd.Flags().StringVar(&fileFlag, "file", "", "read request body from file path ('-' for stdin)")`)
		fmt.Fprintln(b, `			cmd.Flags().StringVar(&jsonFlag, "json", "", "inline request body as a JSON string")`)
		fmt.Fprintln(b, `			cmd.MarkFlagsMutuallyExclusive("file", "json")`)
	}

	fmt.Fprintln(b, "\t\t\tres.AddCommand(cmd)")
	fmt.Fprintln(b, "\t\t}")
}

// flagHelp builds the cobra usage string.
// Format: "[type<format>] description (enum: a|b|c) (required)".
// Empty type/format/description segments are dropped so trivial cases stay clean.
// The redundant `[See details](/enums/Foo)` link the spec attaches to enum
// params is stripped — the inlined `(enum: ...)` makes it dead weight.
func flagHelp(t, format, description string, enum []string, required bool) string {
	var prefix string
	switch {
	case t != "" && format != "":
		prefix = "[" + t + "<" + format + ">] "
	case t != "":
		prefix = "[" + t + "] "
	}
	if len(enum) > 0 {
		description = strings.TrimRight(seeDetailsLink.ReplaceAllString(description, ""), " .")
		if description != "" {
			description += " "
		}
		description += "(enum: " + strings.Join(enum, "|") + ")"
	}
	suffix := ""
	if required {
		suffix = " (required)"
	}
	return prefix + description + suffix
}

func emitTxShortcut(b *bytes.Buffer, s txShortcut, provideVar string) {
	fmt.Fprintln(b, "\t\t{")

	// Flag declarations.
	for _, f := range s.TopFields {
		fmt.Fprintf(b, "\t\t\tvar f_%s string\n", goSafeIdent(f.DotPath))
	}
	for _, p := range s.Params {
		fmt.Fprintf(b, "\t\t\tvar p_%s string\n", goSafeIdent(p.DotPath))
	}
	fmt.Fprintln(b, "\t\t\tvar fileFlag string")
	fmt.Fprintln(b, "\t\t\tvar jsonFlag string")

	fmt.Fprintln(b, "\t\t\tcmd := &cobra.Command{")
	fmt.Fprintf(b, "\t\t\t\tUse:   %q,\n", s.Key)
	fmt.Fprintf(b, "\t\t\t\tShort: %q,\n", "create "+s.Key+" transaction")
	fmt.Fprintln(b, "\t\t\t\tRunE: func(cmd *cobra.Command, args []string) error {")
	fmt.Fprintf(b, "\t\t\t\t\tcli, err := %s()\n", provideVar)
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tbaseline, err := body.Parse(fileFlag, jsonFlag)")
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tfields := map[string]string{")
	fmt.Fprintf(b, "\t\t\t\t\t\t\"transactionType\": %q,\n", s.Key)
	for _, f := range s.TopFields {
		fmt.Fprintf(b, "\t\t\t\t\t\t%q: f_%s,\n", f.DotPath, goSafeIdent(f.DotPath))
	}
	for _, p := range s.Params {
		fmt.Fprintf(b, "\t\t\t\t\t\t%q: p_%s,\n", "params."+p.DotPath, goSafeIdent(p.DotPath))
	}
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tpayload, err := body.Compose(baseline, fields)")
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tif err := qparam.CoerceBodyDates(payload); err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tvar pathParams map[string]string")
	fmt.Fprintln(b, "\t\t\t\t\tvar query interface{}")
	fmt.Fprintln(b, "\t\t\t\t\tvar result interface{}")
	fmt.Fprintln(b, `					if err := cli.Do(cmd.Context(), "POST", "/workspaces/{workspaceId}/transactions", pathParams, payload, query, &result); err != nil {`)
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\treturn output.Print(result)")
	fmt.Fprintln(b, "\t\t\t\t},")
	fmt.Fprintln(b, "\t\t\t}")

	for _, f := range s.TopFields {
		fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&f_%s, %q, \"\", %q)\n",
			goSafeIdent(f.DotPath), f.DotPath, flagHelp(f.Type, f.Format, f.Description, f.Enum, false))
	}
	for _, p := range s.Params {
		fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&p_%s, %q, \"\", %q)\n",
			goSafeIdent(p.DotPath), "params."+p.DotPath, flagHelp(p.Type, p.Format, p.Description, p.Enum, false))
	}
	fmt.Fprintln(b, `			cmd.Flags().StringVar(&fileFlag, "file", "", "read request body from file path ('-' for stdin)")`)
	fmt.Fprintln(b, `			cmd.Flags().StringVar(&jsonFlag, "json", "", "inline request body as a JSON string")`)
	fmt.Fprintln(b, `			cmd.MarkFlagsMutuallyExclusive("file", "json")`)
	fmt.Fprintln(b, "\t\t\tres.AddCommand(cmd)")
	fmt.Fprintln(b, "\t\t}")
}

// emitTxDryRunShortcut mirrors emitTxShortcut but POSTs to /transactions/dry-run
// and attaches the resulting Cobra command to `dryRunCmd` (the generated
// `bron tx dry-run` parent) instead of `res`. Body composition, flag set, and
// fields map are identical — same `CreateTransaction` request shape, same
// `Estimations`-style typed response.
func emitTxDryRunShortcut(b *bytes.Buffer, s txShortcut, provideVar string) {
	fmt.Fprintln(b, "\t\t{")

	for _, f := range s.TopFields {
		fmt.Fprintf(b, "\t\t\tvar f_%s string\n", goSafeIdent(f.DotPath))
	}
	for _, p := range s.Params {
		fmt.Fprintf(b, "\t\t\tvar p_%s string\n", goSafeIdent(p.DotPath))
	}
	fmt.Fprintln(b, "\t\t\tvar fileFlag string")
	fmt.Fprintln(b, "\t\t\tvar jsonFlag string")

	fmt.Fprintln(b, "\t\t\tcmd := &cobra.Command{")
	fmt.Fprintf(b, "\t\t\t\tUse:   %q,\n", s.Key)
	fmt.Fprintf(b, "\t\t\t\tShort: %q,\n", "dry-run "+s.Key+" transaction")
	fmt.Fprintln(b, "\t\t\t\tRunE: func(cmd *cobra.Command, args []string) error {")
	fmt.Fprintf(b, "\t\t\t\t\tcli, err := %s()\n", provideVar)
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tbaseline, err := body.Parse(fileFlag, jsonFlag)")
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tfields := map[string]string{")
	fmt.Fprintf(b, "\t\t\t\t\t\t\"transactionType\": %q,\n", s.Key)
	for _, f := range s.TopFields {
		fmt.Fprintf(b, "\t\t\t\t\t\t%q: f_%s,\n", f.DotPath, goSafeIdent(f.DotPath))
	}
	for _, p := range s.Params {
		fmt.Fprintf(b, "\t\t\t\t\t\t%q: p_%s,\n", "params."+p.DotPath, goSafeIdent(p.DotPath))
	}
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tpayload, err := body.Compose(baseline, fields)")
	fmt.Fprintln(b, "\t\t\t\t\tif err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tif err := qparam.CoerceBodyDates(payload); err != nil {")
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\tvar pathParams map[string]string")
	fmt.Fprintln(b, "\t\t\t\t\tvar query interface{}")
	fmt.Fprintln(b, "\t\t\t\t\tvar result interface{}")
	fmt.Fprintln(b, `					if err := cli.Do(cmd.Context(), "POST", "/workspaces/{workspaceId}/transactions/dry-run", pathParams, payload, query, &result); err != nil {`)
	fmt.Fprintln(b, "\t\t\t\t\t\treturn err")
	fmt.Fprintln(b, "\t\t\t\t\t}")
	fmt.Fprintln(b, "\t\t\t\t\treturn output.Print(result)")
	fmt.Fprintln(b, "\t\t\t\t},")
	fmt.Fprintln(b, "\t\t\t}")

	for _, f := range s.TopFields {
		fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&f_%s, %q, \"\", %q)\n",
			goSafeIdent(f.DotPath), f.DotPath, flagHelp(f.Type, f.Format, f.Description, f.Enum, false))
	}
	for _, p := range s.Params {
		fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&p_%s, %q, \"\", %q)\n",
			goSafeIdent(p.DotPath), "params."+p.DotPath, flagHelp(p.Type, p.Format, p.Description, p.Enum, false))
	}
	fmt.Fprintln(b, `			cmd.Flags().StringVar(&fileFlag, "file", "", "read request body from file path ('-' for stdin)")`)
	fmt.Fprintln(b, `			cmd.Flags().StringVar(&jsonFlag, "json", "", "inline request body as a JSON string")`)
	fmt.Fprintln(b, `			cmd.MarkFlagsMutuallyExclusive("file", "json")`)
	fmt.Fprintln(b, "\t\t\tdryRunCmd.AddCommand(cmd)")
	fmt.Fprintln(b, "\t\t}")
}

func emitHelpers(b *bytes.Buffer) {
	fmt.Fprintln(b, `// compactQuery drops empty string values and coerces date-shaped parameters`)
	fmt.Fprintln(b, `// (createdAtFrom, updatedSince, ...) from ISO-8601 to epoch-millis if needed.`)
	fmt.Fprintln(b, `func compactQuery(m map[string]interface{}) (interface{}, error) {`)
	fmt.Fprintln(b, `	out := map[string]interface{}{}`)
	fmt.Fprintln(b, `	for k, v := range m {`)
	fmt.Fprintln(b, `		s, ok := v.(string)`)
	fmt.Fprintln(b, `		if !ok || s == "" {`)
	fmt.Fprintln(b, `			continue`)
	fmt.Fprintln(b, `		}`)
	fmt.Fprintln(b, `		coerced, err := qparam.MaybeDate(k, s)`)
	fmt.Fprintln(b, `		if err != nil {`)
	fmt.Fprintln(b, `			return nil, err`)
	fmt.Fprintln(b, `		}`)
	fmt.Fprintln(b, `		out[k] = coerced`)
	fmt.Fprintln(b, `	}`)
	fmt.Fprintln(b, `	if len(out) == 0 {`)
	fmt.Fprintln(b, `		return nil, nil`)
	fmt.Fprintln(b, `	}`)
	fmt.Fprintln(b, `	return out, nil`)
	fmt.Fprintln(b, `}`)
}

// emitHelpDoc generates a separate file with the static help map used by
// `bron schema` / `bron help-json` (and any future agent-mode commands).
func emitHelpDoc(plan []plannedCmd, shortcuts []txShortcut) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by cligen. DO NOT EDIT.")
	fmt.Fprintln(&b, "package generated")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type HelpEntry struct {")
	fmt.Fprintln(&b, "\tMethod       string")
	fmt.Fprintln(&b, "\tPath         string")
	fmt.Fprintln(&b, "\tBodyRef      string")
	fmt.Fprintln(&b, "\tResponseRef  string")
	fmt.Fprintln(&b, "\tQueryParams  []HelpQueryParam")
	fmt.Fprintln(&b, "\tPathArgs     []string")
	fmt.Fprintln(&b, "\tEmbedTokens  []string // valid --embed values, derived from includeXxx query params")
	fmt.Fprintln(&b, "\tPermissions  []string // API key permissions allowed, e.g. [\"View only\", \"Transaction Operator\"] — used by `bron mcp --read-only`")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type HelpQueryParam struct {")
	fmt.Fprintln(&b, "\tName        string")
	fmt.Fprintln(&b, "\tRequired    bool")
	fmt.Fprintln(&b, "\tType        string // OpenAPI type — \"string\" | \"integer\" | \"boolean\" | \"number\" | \"array\". \"string[]\" / \"integer[]\" for array of primitive.")
	fmt.Fprintln(&b, "\tFormat      string // OpenAPI format — \"int64\" | \"date-time-millis\" | \"decimal\" | ...")
	fmt.Fprintln(&b, "\tDescription string")
	fmt.Fprintln(&b, "\tEnum        []string")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type TxShortcut struct {")
	fmt.Fprintln(&b, "\tParamsRef string")
	fmt.Fprintln(&b, "\tParams    []string")
	fmt.Fprintln(&b, "\tTopFields []string")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "var HelpEntries = map[string]map[string]HelpEntry{")
	for _, g := range groupByResource(plan) {
		fmt.Fprintf(&b, "\t%q: {\n", g.Name)
		for _, c := range g.Commands {
			fmt.Fprintf(&b, "\t\t%q: {Method: %q, Path: %q, BodyRef: %q, ResponseRef: %q",
				c.Verb, c.Method, c.Path, c.BodyRef, c.ResponseRef)
			if len(c.PathArgs) > 0 {
				fmt.Fprint(&b, ", PathArgs: []string{")
				for i, a := range c.PathArgs {
					if i > 0 {
						fmt.Fprint(&b, ", ")
					}
					fmt.Fprintf(&b, "%q", a)
				}
				fmt.Fprint(&b, "}")
			}
			if len(c.QueryParams) > 0 {
				fmt.Fprint(&b, ", QueryParams: []HelpQueryParam{")
				for i, q := range c.QueryParams {
					if i > 0 {
						fmt.Fprint(&b, ", ")
					}
					fmt.Fprintf(&b, "{Name: %q, Required: %t", q.Name, q.Required)
					if q.Type != "" {
						fmt.Fprintf(&b, ", Type: %q", q.Type)
					}
					if q.Format != "" {
						fmt.Fprintf(&b, ", Format: %q", q.Format)
					}
					if q.Description != "" {
						fmt.Fprintf(&b, ", Description: %q", q.Description)
					}
					if len(q.Enum) > 0 {
						fmt.Fprint(&b, ", Enum: []string{")
						for j, e := range q.Enum {
							if j > 0 {
								fmt.Fprint(&b, ", ")
							}
							fmt.Fprintf(&b, "%q", e)
						}
						fmt.Fprint(&b, "}")
					}
					fmt.Fprint(&b, "}")
				}
				fmt.Fprint(&b, "}")
			}
			if tokens := c.embedTokens(); len(tokens) > 0 {
				fmt.Fprint(&b, ", EmbedTokens: []string{")
				for i, t := range tokens {
					if i > 0 {
						fmt.Fprint(&b, ", ")
					}
					fmt.Fprintf(&b, "%q", t)
				}
				fmt.Fprint(&b, "}")
			}
			if len(c.Permissions) > 0 {
				fmt.Fprint(&b, ", Permissions: []string{")
				for i, p := range c.Permissions {
					if i > 0 {
						fmt.Fprint(&b, ", ")
					}
					fmt.Fprintf(&b, "%q", p)
				}
				fmt.Fprint(&b, "}")
			}
			fmt.Fprintln(&b, "},")
		}
		fmt.Fprintln(&b, "\t},")
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "var TxShortcuts = map[string]TxShortcut{")
	for _, s := range shortcuts {
		fmt.Fprintf(&b, "\t%q: {ParamsRef: %q, ", s.Key, s.Class)
		fmt.Fprint(&b, "Params: []string{")
		for i, p := range s.Params {
			if i > 0 {
				fmt.Fprint(&b, ", ")
			}
			fmt.Fprintf(&b, "%q", p.DotPath)
		}
		fmt.Fprint(&b, "}, TopFields: []string{")
		for i, f := range s.TopFields {
			if i > 0 {
				fmt.Fprint(&b, ", ")
			}
			fmt.Fprintf(&b, "%q", f.DotPath)
		}
		fmt.Fprintln(&b, "}},")
	}
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("gofmt helpdoc: %w", err)
	}
	return formatted, nil
}

// goSafeIdent converts a string into a Go-safe identifier suffix.
// Keeps alphanumerics, replaces other runes with underscore.
func goSafeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	if b.Len() == 0 {
		return "_"
	}
	return b.String()
}
